name: Link Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.6
      with:
        args: --exclude https://twitter.com/.* --exclude a@b.com --exclude c@d.com --verbose README.md src/*.md

    - name: Fail if there were link errors
      run: exit ${{ steps.lychee.outputs.exit_code }}
