name: Link Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.4
      with:
        args: -v README.md src/*.md

    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
